/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

let JsonRemoteCodec$schema$value
const JsonRemoteCodec$schema = () => (JsonRemoteCodec$schema$value ??= z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()]))
let JsonRemoteCodec$schema2$value
const JsonRemoteCodec$schema2 = () => (JsonRemoteCodec$schema2$value ??= z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema2())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema2())).readonly()]))
let _dsh_jev_plugin_jev_cancelStageAnalysis_parameter_0$schema$value
const _dsh_jev_plugin_jev_cancelStageAnalysis_parameter_0$schema = () => (_dsh_jev_plugin_jev_cancelStageAnalysis_parameter_0$schema$value ??= z.string())
let _dsh_jev_plugin_jev_cancelStageAnalysis_result$schema$value
const _dsh_jev_plugin_jev_cancelStageAnalysis_result$schema = () => (_dsh_jev_plugin_jev_cancelStageAnalysis_result$schema$value ??= z.void())
let _dsh_jev_plugin_jev_getCredentialStatus_parameter_0$schema$value
const _dsh_jev_plugin_jev_getCredentialStatus_parameter_0$schema = () => (_dsh_jev_plugin_jev_getCredentialStatus_parameter_0$schema$value ??= z.object({
  'connectionId': z.union([z.literal("jev"), z.literal("luna-openrouter"), z.literal("luna-openai")]),
  'baseUrl': z.string(),
  'model': z.string(),
  'credentialRef': z.string(),
  'timeoutMs': z.number(),
}))
let _dsh_jev_plugin_jev_getCredentialStatus_result$schema$value
const _dsh_jev_plugin_jev_getCredentialStatus_result$schema = () => (_dsh_jev_plugin_jev_getCredentialStatus_result$schema$value ??= z.object({
  'connection': z.object({
  'connectionId': z.union([z.literal("jev"), z.literal("luna-openrouter"), z.literal("luna-openai")]),
  'baseUrl': z.string(),
  'model': z.string(),
  'credentialRef': z.string(),
  'timeoutMs': z.number(),
}),
  'configured': z.boolean(),
  'writable': z.boolean(),
  'source': z.union([z.undefined(), z.string()]).optional(),
}))
let _dsh_jev_plugin_jev_getRecord_parameter_0$schema$value
const _dsh_jev_plugin_jev_getRecord_parameter_0$schema = () => (_dsh_jev_plugin_jev_getRecord_parameter_0$schema$value ??= z.string())
let _dsh_jev_plugin_jev_getRecord_result$schema$value
const _dsh_jev_plugin_jev_getRecord_result$schema = () => (_dsh_jev_plugin_jev_getRecord_result$schema$value ??= z.union([z.literal(null), z.object({
  'link': z.object({
  'sessionId': z.union([z.undefined(), z.string()]).optional(),
  'runId': z.union([z.undefined(), z.string()]).optional(),
  'stepId': z.union([z.undefined(), z.string()]).optional(),
  'inputVersion': z.union([z.undefined(), z.string()]).optional(),
}),
  'attemptRecords': z.array(z.object({
  'id': z.string(),
  'startedAt': z.string(),
  'settledAt': z.union([z.undefined(), z.string()]).optional(),
  'latencyMs': z.union([z.undefined(), z.number()]).optional(),
  'connection': z.object({
  'baseUrl': z.string(),
  'model': z.string(),
  'credentialRef': z.string(),
  'connectionId': z.union([z.undefined(), z.literal("jev"), z.literal("luna-openrouter"), z.literal("luna-openai")]).optional(),
}),
  'request': z.object({
  'state': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()]),
  'questions': z.array(z.union([z.object({
  'id': z.string(),
  'kind': z.literal("choice"),
  'prompt': z.union([z.string(), z.array(z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()])), z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()])).readonly()]),
  'options': z.array(z.object({
  'id': z.string(),
  'description': z.union([z.literal(null), z.string(), z.array(z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()])), z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()])).readonly()]),
})),
}), z.object({
  'id': z.string(),
  'kind': z.literal("score"),
  'prompt': z.union([z.string(), z.array(z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()])), z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()])).readonly()]),
  'levels': z.array(z.union([z.literal(null), z.string(), z.array(z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()])), z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()])).readonly()])),
}), z.object({
  'id': z.string(),
  'kind': z.literal("noul"),
  'prompt': z.union([z.string(), z.array(z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()])), z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()])).readonly()]),
  'criteria': z.union([z.undefined(), z.object({
  'true': z.union([z.undefined(), z.literal(null), z.string(), z.array(z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()])), z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()])).readonly()]).optional(),
  'false': z.union([z.undefined(), z.literal(null), z.string(), z.array(z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()])), z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()])).readonly()]).optional(),
})]).optional(),
})])),
}),
  'status': z.union([z.literal("pending"), z.literal("waiting"), z.literal("succeeded"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]),
  'rawResponse': z.union([z.undefined(), z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()]).optional(),
  'response': z.union([z.undefined(), z.object({
  'answers': z.array(z.union([z.object({
  'id': z.string(),
  'kind': z.literal("choice"),
  'optionId': z.string(),
  'probabilities': z.union([z.undefined(), z.record(z.string(), z.number())]).optional(),
  'confidence': z.union([z.undefined(), z.number()]).optional(),
  'legend': z.union([z.undefined(), z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()]).optional(),
}), z.object({
  'id': z.string(),
  'kind': z.literal("score"),
  'value': z.number(),
  'probabilities': z.union([z.undefined(), z.record(z.string(), z.number())]).optional(),
  'confidence': z.union([z.undefined(), z.number()]).optional(),
  'legend': z.union([z.undefined(), z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()]).optional(),
}), z.object({
  'id': z.string(),
  'kind': z.literal("noul"),
  'probability': z.number(),
  'confidence': z.union([z.undefined(), z.number()]).optional(),
  'legend': z.union([z.undefined(), z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()]).optional(),
})])),
})]).optional(),
  'interpretation': z.union([z.undefined(), z.object({
  'usable': z.boolean(),
  'reason': z.union([z.undefined(), z.string()]).optional(),
})]).optional(),
  'failure': z.union([z.undefined(), z.object({
  'code': z.string(),
  'message': z.string(),
})]).optional(),
  'usage': z.union([z.undefined(), z.object({
  'inputTokens': z.union([z.undefined(), z.number()]).optional(),
  'outputTokens': z.union([z.undefined(), z.number()]).optional(),
})]).optional(),
  'networkRecords': z.union([z.undefined(), z.array(z.object({
  'id': z.string(),
  'questionIds': z.array(z.string()),
  'requestBody': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()]),
  'startedAt': z.string(),
  'dispatchedAt': z.union([z.undefined(), z.string()]).optional(),
  'settledAt': z.union([z.undefined(), z.string()]).optional(),
  'status': z.union([z.literal("pending"), z.literal("succeeded"), z.literal("failed")]),
  'httpStatus': z.union([z.undefined(), z.number()]).optional(),
  'rawResponseText': z.union([z.undefined(), z.string()]).optional(),
  'rawResponse': z.union([z.undefined(), z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()]).optional(),
  'returnedModel': z.union([z.undefined(), z.string()]).optional(),
  'requestId': z.union([z.undefined(), z.string()]).optional(),
  'usage': z.union([z.undefined(), z.object({
  'inputTokens': z.union([z.undefined(), z.number()]).optional(),
  'outputTokens': z.union([z.undefined(), z.number()]).optional(),
})]).optional(),
  'failure': z.union([z.undefined(), z.object({
  'code': z.string(),
  'message': z.string(),
})]).optional(),
}))]).optional(),
  'usageComplete': z.union([z.undefined(), z.literal(false), z.literal(true)]).optional(),
})),
  'receipts': z.array(z.object({
  'id': z.string(),
  'status': z.union([z.literal("cancelled"), z.literal("unconfirmed"), z.literal("not-adopted"), z.literal("executed"), z.literal("execution-failed"), z.literal("observed")]),
  'reason': z.union([z.undefined(), z.string()]).optional(),
  'at': z.string(),
})),
  'failure': z.union([z.undefined(), z.object({
  'code': z.string(),
  'message': z.string(),
})]).optional(),
  'id': z.string(),
  'featureId': z.string(),
  'sessionId': z.union([z.undefined(), z.string()]).optional(),
  'status': z.union([z.literal("pending"), z.literal("waiting"), z.literal("succeeded"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]),
  'startedAt': z.string(),
  'updatedAt': z.string(),
  'attempts': z.number(),
  'actionStatus': z.union([z.undefined(), z.literal("cancelled"), z.literal("unconfirmed"), z.literal("not-adopted"), z.literal("executed"), z.literal("execution-failed"), z.literal("observed")]).optional(),
  'diagnostic': z.boolean(),
})]))
let _dsh_jev_plugin_jev_getStageAnalysisRecord_parameter_0$schema$value
const _dsh_jev_plugin_jev_getStageAnalysisRecord_parameter_0$schema = () => (_dsh_jev_plugin_jev_getStageAnalysisRecord_parameter_0$schema$value ??= z.string())
let _dsh_jev_plugin_jev_getStageAnalysisRecord_parameter_1$schema$value
const _dsh_jev_plugin_jev_getStageAnalysisRecord_parameter_1$schema = () => (_dsh_jev_plugin_jev_getStageAnalysisRecord_parameter_1$schema$value ??= z.string())
let _dsh_jev_plugin_jev_getStageAnalysisRecord_parameter_2$schema$value
const _dsh_jev_plugin_jev_getStageAnalysisRecord_parameter_2$schema = () => (_dsh_jev_plugin_jev_getStageAnalysisRecord_parameter_2$schema$value ??= z.union([z.undefined(), z.string()]))
let _dsh_jev_plugin_jev_getStageAnalysisRecord_result$schema$value
const _dsh_jev_plugin_jev_getStageAnalysisRecord_result$schema = () => (_dsh_jev_plugin_jev_getStageAnalysisRecord_result$schema$value ??= z.union([z.literal(null), z.object({
  'id': z.string(),
  'sessionId': z.string(),
  'stepId': z.string(),
  'revision': z.number(),
  'sourceFingerprint': z.string(),
  'ruleVersion': z.string(),
  'request': z.union([z.undefined(), z.object({
  'state': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema2())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema2())).readonly()]),
  'questions': z.array(z.union([z.object({
  'id': z.string(),
  'kind': z.literal("choice"),
  'prompt': z.union([z.string(), z.array(z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema2())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema2())).readonly()])), z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema2())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema2())).readonly()])).readonly()]),
  'options': z.array(z.object({
  'id': z.string(),
  'description': z.union([z.literal(null), z.string(), z.array(z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema2())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema2())).readonly()])), z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema2())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema2())).readonly()])).readonly()]),
})),
}), z.object({
  'id': z.string(),
  'kind': z.literal("score"),
  'prompt': z.union([z.string(), z.array(z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema2())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema2())).readonly()])), z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema2())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema2())).readonly()])).readonly()]),
  'levels': z.array(z.union([z.literal(null), z.string(), z.array(z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema2())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema2())).readonly()])), z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema2())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema2())).readonly()])).readonly()])),
}), z.object({
  'id': z.string(),
  'kind': z.literal("noul"),
  'prompt': z.union([z.string(), z.array(z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema2())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema2())).readonly()])), z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema2())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema2())).readonly()])).readonly()]),
  'criteria': z.union([z.undefined(), z.object({
  'true': z.union([z.undefined(), z.literal(null), z.string(), z.array(z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema2())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema2())).readonly()])), z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema2())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema2())).readonly()])).readonly()]).optional(),
  'false': z.union([z.undefined(), z.literal(null), z.string(), z.array(z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema2())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema2())).readonly()])), z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema2())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema2())).readonly()])).readonly()]).optional(),
})]).optional(),
})])),
})]).optional(),
  'response': z.union([z.undefined(), z.object({
  'answers': z.array(z.union([z.object({
  'id': z.string(),
  'kind': z.literal("choice"),
  'optionId': z.string(),
  'probabilities': z.union([z.undefined(), z.record(z.string(), z.number())]).optional(),
  'confidence': z.union([z.undefined(), z.number()]).optional(),
  'legend': z.union([z.undefined(), z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema2())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema2())).readonly()]).optional(),
}), z.object({
  'id': z.string(),
  'kind': z.literal("score"),
  'value': z.number(),
  'probabilities': z.union([z.undefined(), z.record(z.string(), z.number())]).optional(),
  'confidence': z.union([z.undefined(), z.number()]).optional(),
  'legend': z.union([z.undefined(), z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema2())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema2())).readonly()]).optional(),
}), z.object({
  'id': z.string(),
  'kind': z.literal("noul"),
  'probability': z.number(),
  'confidence': z.union([z.undefined(), z.number()]).optional(),
  'legend': z.union([z.undefined(), z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema2())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema2())).readonly()]).optional(),
})])),
})]).optional(),
  'rawResponse': z.union([z.undefined(), z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema2())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema2())).readonly()]).optional(),
  'connection': z.union([z.undefined(), z.object({
  'baseUrl': z.string(),
  'model': z.string(),
  'credentialRef': z.string(),
  'connectionId': z.union([z.undefined(), z.literal("jev"), z.literal("luna-openrouter"), z.literal("luna-openai")]).optional(),
})]).optional(),
  'networkRecords': z.union([z.undefined(), z.array(z.object({
  'id': z.string(),
  'questionIds': z.array(z.string()),
  'requestBody': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema2())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema2())).readonly()]),
  'startedAt': z.string(),
  'dispatchedAt': z.union([z.undefined(), z.string()]).optional(),
  'settledAt': z.union([z.undefined(), z.string()]).optional(),
  'status': z.union([z.literal("pending"), z.literal("succeeded"), z.literal("failed")]),
  'httpStatus': z.union([z.undefined(), z.number()]).optional(),
  'rawResponseText': z.union([z.undefined(), z.string()]).optional(),
  'rawResponse': z.union([z.undefined(), z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema2())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema2())).readonly()]).optional(),
  'returnedModel': z.union([z.undefined(), z.string()]).optional(),
  'requestId': z.union([z.undefined(), z.string()]).optional(),
  'usage': z.union([z.undefined(), z.object({
  'inputTokens': z.union([z.undefined(), z.number()]).optional(),
  'outputTokens': z.union([z.undefined(), z.number()]).optional(),
})]).optional(),
  'failure': z.union([z.undefined(), z.object({
  'code': z.string(),
  'message': z.string(),
})]).optional(),
}))]).optional(),
  'usage': z.union([z.undefined(), z.object({
  'inputTokens': z.union([z.undefined(), z.number()]).optional(),
  'outputTokens': z.union([z.undefined(), z.number()]).optional(),
})]).optional(),
  'usageComplete': z.union([z.undefined(), z.literal(false), z.literal(true)]).optional(),
  'status': z.union([z.literal("pending"), z.literal("succeeded"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted"), z.literal("unanalysed"), z.literal("stale"), z.literal("unavailable")]),
  'label': z.union([z.undefined(), z.literal("input_parsing"), z.literal("problem_understanding"), z.literal("solution_planning"), z.literal("implementation"), z.literal("review_validation"), z.literal("delivery_finalization"), z.literal("mixed"), z.literal("unknown")]).optional(),
  'confidence': z.union([z.undefined(), z.number()]).optional(),
  'probabilities': z.union([z.undefined(), z.record(z.string(), z.number())]).optional(),
  'model': z.union([z.undefined(), z.string()]).optional(),
  'configuredModel': z.union([z.undefined(), z.string()]).optional(),
  'connectionId': z.union([z.undefined(), z.literal("jev"), z.literal("luna-openrouter"), z.literal("luna-openai")]).optional(),
  'recordId': z.union([z.undefined(), z.string()]).optional(),
  'operationId': z.union([z.undefined(), z.string()]).optional(),
  'failure': z.union([z.undefined(), z.object({
  'code': z.string(),
  'message': z.string(),
})]).optional(),
  'updatedAt': z.union([z.undefined(), z.string()]).optional(),
  'previousResult': z.union([z.undefined(), z.object({
  'recordId': z.string(),
  'label': z.union([z.literal("input_parsing"), z.literal("problem_understanding"), z.literal("solution_planning"), z.literal("implementation"), z.literal("review_validation"), z.literal("delivery_finalization"), z.literal("mixed"), z.literal("unknown")]),
  'stale': z.boolean(),
  'confidence': z.union([z.undefined(), z.number()]).optional(),
  'probabilities': z.union([z.undefined(), z.record(z.string(), z.number())]).optional(),
  'model': z.union([z.undefined(), z.string()]).optional(),
  'configuredModel': z.union([z.undefined(), z.string()]).optional(),
  'connectionId': z.union([z.undefined(), z.literal("jev"), z.literal("luna-openrouter"), z.literal("luna-openai")]).optional(),
  'updatedAt': z.union([z.undefined(), z.string()]).optional(),
})]).optional(),
})]))
let _dsh_jev_plugin_jev_getStageNavigation_parameter_0$schema$value
const _dsh_jev_plugin_jev_getStageNavigation_parameter_0$schema = () => (_dsh_jev_plugin_jev_getStageNavigation_parameter_0$schema$value ??= z.string())
let _dsh_jev_plugin_jev_getStageNavigation_result$schema$value
const _dsh_jev_plugin_jev_getStageNavigation_result$schema = () => (_dsh_jev_plugin_jev_getStageNavigation_result$schema$value ??= z.object({
  'sessionId': z.string(),
  'cursor': z.number(),
  'featureEnabled': z.boolean(),
  'turns': z.array(z.object({
  'id': z.string(),
  'turn': z.number(),
  'startSeq': z.number(),
  'endSeq': z.union([z.undefined(), z.number()]).optional(),
  'reason': z.union([z.undefined(), z.object({
  'kind': z.literal("interrupted"),
}), z.object({
  'kind': z.literal("completed"),
}), z.object({
  'kind': z.literal("aborted"),
  'reason': z.union([z.object({
  'kind': z.literal("user").readonly(),
}), z.object({
  'kind': z.literal("parent").readonly(),
}), z.object({
  'kind': z.literal("hook").readonly(),
  'reason': z.string().readonly(),
}), z.object({
  'kind': z.literal("disposed").readonly(),
}), z.object({
  'kind': z.literal("legacy").readonly(),
})]),
}), z.object({
  'kind': z.literal("blocked"),
}), z.object({
  'kind': z.literal("error"),
  'error': z.object({
  'message': z.string().readonly(),
  'code': z.string().readonly(),
  'status': z.union([z.undefined(), z.number()]).readonly().optional(),
  'providerRetryAfterMs': z.union([z.undefined(), z.number()]).readonly().optional(),
  'requestId': z.union([z.undefined(), z.intersection(z.string(), z.unknown())]).readonly().optional(),
  'offloadImages': z.union([z.undefined(), z.number()]).readonly().optional(),
}),
}), z.object({
  'kind': z.literal("max-tokens"),
}), z.object({
  'kind': z.literal("forked"),
})]).optional(),
  'requests': z.array(z.object({
  'seq': z.number(),
  'content': z.array(z.union([z.object({
  'type': z.literal("text"),
  'text': z.string(),
}), z.object({
  'type': z.literal("reasoning"),
  'text': z.string(),
}), z.object({
  'type': z.literal("image"),
  'attachment': z.object({
  'attachmentId': z.intersection(z.string(), z.unknown()),
  'mediaType': z.union([z.literal("image/png"), z.literal("image/jpeg"), z.literal("image/webp"), z.literal("image/gif")]),
  'bytes': z.number(),
  'width': z.number(),
  'height': z.number(),
  'name': z.union([z.undefined(), z.string()]).optional(),
  'originalDimensions': z.union([z.undefined(), z.object({
  'width': z.number(),
  'height': z.number(),
})]).optional(),
}),
  'offloaded': z.union([z.undefined(), z.literal(true)]).optional(),
}), z.object({
  'type': z.literal("file"),
  'attachment': z.object({
  'attachmentId': z.intersection(z.string(), z.unknown()),
  'name': z.string(),
  'bytes': z.number(),
}),
}), z.object({
  'type': z.literal("tool-call"),
  'id': z.intersection(z.string(), z.unknown()),
  'name': z.string(),
  'arguments': z.string(),
}), z.object({
  'type': z.literal("tool-addition"),
  'toolName': z.string(),
  'tool': z.undefined().optional(),
}), z.object({
  'type': z.literal("tool-removal"),
  'toolName': z.string(),
})])),
})),
  'steps': z.array(z.object({
  'id': z.string(),
  'turn': z.number(),
  'step': z.number(),
  'startSeq': z.number(),
  'endSeq': z.union([z.undefined(), z.number()]).optional(),
  'status': z.union([z.literal("complete"), z.literal("terminal-partial"), z.literal("in-progress")]),
  'classifiable': z.boolean(),
  'materialStatus': z.union([z.literal("ready"), z.literal("IN_PROGRESS"), z.literal("NO_MATERIAL"), z.literal("MATERIAL_TOO_LARGE")]),
  'assistant': z.union([z.undefined(), z.intersection(z.object({
  'seq': z.number(),
  'content': z.array(z.union([z.object({
  'type': z.literal("text"),
  'text': z.string(),
}), z.object({
  'type': z.literal("reasoning"),
  'text': z.string(),
}), z.object({
  'type': z.literal("image"),
  'attachment': z.object({
  'attachmentId': z.intersection(z.string(), z.unknown()),
  'mediaType': z.union([z.literal("image/png"), z.literal("image/jpeg"), z.literal("image/webp"), z.literal("image/gif")]),
  'bytes': z.number(),
  'width': z.number(),
  'height': z.number(),
  'name': z.union([z.undefined(), z.string()]).optional(),
  'originalDimensions': z.union([z.undefined(), z.object({
  'width': z.number(),
  'height': z.number(),
})]).optional(),
}),
  'offloaded': z.union([z.undefined(), z.literal(true)]).optional(),
}), z.object({
  'type': z.literal("file"),
  'attachment': z.object({
  'attachmentId': z.intersection(z.string(), z.unknown()),
  'name': z.string(),
  'bytes': z.number(),
}),
}), z.object({
  'type': z.literal("tool-call"),
  'id': z.intersection(z.string(), z.unknown()),
  'name': z.string(),
  'arguments': z.string(),
}), z.object({
  'type': z.literal("tool-addition"),
  'toolName': z.string(),
  'tool': z.undefined().optional(),
}), z.object({
  'type': z.literal("tool-removal"),
  'toolName': z.string(),
})])),
}), z.object({
  'interrupted': z.boolean(),
}))]).optional(),
  'messages': z.array(z.intersection(z.object({
  'seq': z.number(),
  'content': z.array(z.union([z.object({
  'type': z.literal("text"),
  'text': z.string(),
}), z.object({
  'type': z.literal("reasoning"),
  'text': z.string(),
}), z.object({
  'type': z.literal("image"),
  'attachment': z.object({
  'attachmentId': z.intersection(z.string(), z.unknown()),
  'mediaType': z.union([z.literal("image/png"), z.literal("image/jpeg"), z.literal("image/webp"), z.literal("image/gif")]),
  'bytes': z.number(),
  'width': z.number(),
  'height': z.number(),
  'name': z.union([z.undefined(), z.string()]).optional(),
  'originalDimensions': z.union([z.undefined(), z.object({
  'width': z.number(),
  'height': z.number(),
})]).optional(),
}),
  'offloaded': z.union([z.undefined(), z.literal(true)]).optional(),
}), z.object({
  'type': z.literal("file"),
  'attachment': z.object({
  'attachmentId': z.intersection(z.string(), z.unknown()),
  'name': z.string(),
  'bytes': z.number(),
}),
}), z.object({
  'type': z.literal("tool-call"),
  'id': z.intersection(z.string(), z.unknown()),
  'name': z.string(),
  'arguments': z.string(),
}), z.object({
  'type': z.literal("tool-addition"),
  'toolName': z.string(),
  'tool': z.undefined().optional(),
}), z.object({
  'type': z.literal("tool-removal"),
  'toolName': z.string(),
})])),
}), z.object({
  'interrupted': z.boolean(),
}))),
  'tools': z.array(z.object({
  'callId': z.string(),
  'name': z.string(),
  'arguments': z.string(),
  'seq': z.number(),
  'dispatched': z.boolean(),
  'result': z.union([z.undefined(), z.intersection(z.object({
  'seq': z.number(),
  'content': z.array(z.union([z.object({
  'type': z.literal("text"),
  'text': z.string(),
}), z.object({
  'type': z.literal("reasoning"),
  'text': z.string(),
}), z.object({
  'type': z.literal("image"),
  'attachment': z.object({
  'attachmentId': z.intersection(z.string(), z.unknown()),
  'mediaType': z.union([z.literal("image/png"), z.literal("image/jpeg"), z.literal("image/webp"), z.literal("image/gif")]),
  'bytes': z.number(),
  'width': z.number(),
  'height': z.number(),
  'name': z.union([z.undefined(), z.string()]).optional(),
  'originalDimensions': z.union([z.undefined(), z.object({
  'width': z.number(),
  'height': z.number(),
})]).optional(),
}),
  'offloaded': z.union([z.undefined(), z.literal(true)]).optional(),
}), z.object({
  'type': z.literal("file"),
  'attachment': z.object({
  'attachmentId': z.intersection(z.string(), z.unknown()),
  'name': z.string(),
  'bytes': z.number(),
}),
}), z.object({
  'type': z.literal("tool-call"),
  'id': z.intersection(z.string(), z.unknown()),
  'name': z.string(),
  'arguments': z.string(),
}), z.object({
  'type': z.literal("tool-addition"),
  'toolName': z.string(),
  'tool': z.undefined().optional(),
}), z.object({
  'type': z.literal("tool-removal"),
  'toolName': z.string(),
})])),
}), z.object({
  'isError': z.boolean(),
  'error': z.union([z.undefined(), z.object({
  'name': z.string(),
  'code': z.string(),
  'reason': z.union([z.undefined(), z.string()]).optional(),
})]).optional(),
}))]).optional(),
})),
  'attemptSeqs': z.array(z.number()),
  'analysis': z.object({
  'status': z.union([z.literal("pending"), z.literal("succeeded"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted"), z.literal("unanalysed"), z.literal("stale"), z.literal("unavailable")]),
  'label': z.union([z.undefined(), z.literal("input_parsing"), z.literal("problem_understanding"), z.literal("solution_planning"), z.literal("implementation"), z.literal("review_validation"), z.literal("delivery_finalization"), z.literal("mixed"), z.literal("unknown")]).optional(),
  'confidence': z.union([z.undefined(), z.number()]).optional(),
  'probabilities': z.union([z.undefined(), z.record(z.string(), z.number())]).optional(),
  'model': z.union([z.undefined(), z.string()]).optional(),
  'configuredModel': z.union([z.undefined(), z.string()]).optional(),
  'connectionId': z.union([z.undefined(), z.literal("jev"), z.literal("luna-openrouter"), z.literal("luna-openai")]).optional(),
  'recordId': z.union([z.undefined(), z.string()]).optional(),
  'operationId': z.union([z.undefined(), z.string()]).optional(),
  'failure': z.union([z.undefined(), z.object({
  'code': z.string(),
  'message': z.string(),
})]).optional(),
  'updatedAt': z.union([z.undefined(), z.string()]).optional(),
  'previousResult': z.union([z.undefined(), z.object({
  'recordId': z.string(),
  'label': z.union([z.literal("input_parsing"), z.literal("problem_understanding"), z.literal("solution_planning"), z.literal("implementation"), z.literal("review_validation"), z.literal("delivery_finalization"), z.literal("mixed"), z.literal("unknown")]),
  'stale': z.boolean(),
  'confidence': z.union([z.undefined(), z.number()]).optional(),
  'probabilities': z.union([z.undefined(), z.record(z.string(), z.number())]).optional(),
  'model': z.union([z.undefined(), z.string()]).optional(),
  'configuredModel': z.union([z.undefined(), z.string()]).optional(),
  'connectionId': z.union([z.undefined(), z.literal("jev"), z.literal("luna-openrouter"), z.literal("luna-openai")]).optional(),
  'updatedAt': z.union([z.undefined(), z.string()]).optional(),
})]).optional(),
}),
})),
})),
  'batch': z.union([z.undefined(), z.object({
  'id': z.string(),
  'sessionId': z.string(),
  'status': z.union([z.literal("failed"), z.literal("cancelled"), z.literal("completed"), z.literal("running")]),
  'total': z.number(),
  'completed': z.number(),
  'failed': z.number(),
  'cancelled': z.number(),
  'failure': z.union([z.undefined(), z.object({
  'code': z.string(),
  'message': z.string(),
})]).optional(),
})]).optional(),
}))
let _dsh_jev_plugin_jev_listFeatures_result$schema$value
const _dsh_jev_plugin_jev_listFeatures_result$schema = () => (_dsh_jev_plugin_jev_listFeatures_result$schema$value ??= z.array(z.object({
  'enabled': z.boolean(),
  'id': z.string(),
  'name': z.string(),
  'description': z.string(),
  'settingsDescription': z.union([z.undefined(), z.string()]).optional(),
})))
let _dsh_jev_plugin_jev_listRecords_parameter_0$schema$value
const _dsh_jev_plugin_jev_listRecords_parameter_0$schema = () => (_dsh_jev_plugin_jev_listRecords_parameter_0$schema$value ??= z.object({
  'featureId': z.union([z.undefined(), z.string()]).optional(),
  'status': z.union([z.undefined(), z.literal("pending"), z.literal("waiting"), z.literal("succeeded"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]).optional(),
  'sessionId': z.union([z.undefined(), z.string()]).optional(),
  'cursor': z.union([z.undefined(), z.string()]).optional(),
  'limit': z.union([z.undefined(), z.number()]).optional(),
}))
let _dsh_jev_plugin_jev_listRecords_result$schema$value
const _dsh_jev_plugin_jev_listRecords_result$schema = () => (_dsh_jev_plugin_jev_listRecords_result$schema$value ??= z.object({
  'items': z.array(z.object({
  'id': z.string(),
  'featureId': z.string(),
  'sessionId': z.union([z.undefined(), z.string()]).optional(),
  'status': z.union([z.literal("pending"), z.literal("waiting"), z.literal("succeeded"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]),
  'startedAt': z.string(),
  'updatedAt': z.string(),
  'attempts': z.number(),
  'actionStatus': z.union([z.undefined(), z.literal("cancelled"), z.literal("unconfirmed"), z.literal("not-adopted"), z.literal("executed"), z.literal("execution-failed"), z.literal("observed")]).optional(),
  'diagnostic': z.boolean(),
})),
  'nextCursor': z.union([z.undefined(), z.string()]).optional(),
}))
let _dsh_jev_plugin_jev_setCredential_parameter_0$schema$value
const _dsh_jev_plugin_jev_setCredential_parameter_0$schema = () => (_dsh_jev_plugin_jev_setCredential_parameter_0$schema$value ??= z.object({
  'connectionId': z.union([z.literal("jev"), z.literal("luna-openrouter"), z.literal("luna-openai")]),
  'baseUrl': z.string(),
  'model': z.string(),
  'credentialRef': z.string(),
  'timeoutMs': z.number(),
}))
let _dsh_jev_plugin_jev_setCredential_parameter_1$schema$value
const _dsh_jev_plugin_jev_setCredential_parameter_1$schema = () => (_dsh_jev_plugin_jev_setCredential_parameter_1$schema$value ??= z.string())
let _dsh_jev_plugin_jev_setCredential_result$schema$value
const _dsh_jev_plugin_jev_setCredential_result$schema = () => (_dsh_jev_plugin_jev_setCredential_result$schema$value ??= z.object({
  'connection': z.object({
  'connectionId': z.union([z.literal("jev"), z.literal("luna-openrouter"), z.literal("luna-openai")]),
  'baseUrl': z.string(),
  'model': z.string(),
  'credentialRef': z.string(),
  'timeoutMs': z.number(),
}),
  'configured': z.boolean(),
  'writable': z.boolean(),
  'source': z.union([z.undefined(), z.string()]).optional(),
}))
let _dsh_jev_plugin_jev_startStageAnalysis_parameter_0$schema$value
const _dsh_jev_plugin_jev_startStageAnalysis_parameter_0$schema = () => (_dsh_jev_plugin_jev_startStageAnalysis_parameter_0$schema$value ??= z.object({
  'sessionId': z.string(),
  'scope': z.union([z.object({
  'kind': z.literal("turn"),
  'turn': z.number(),
}), z.object({
  'kind': z.literal("all"),
})]),
  'mode': z.union([z.literal("missing"), z.literal("retry-failed"), z.literal("refresh")]),
}))
let _dsh_jev_plugin_jev_startStageAnalysis_result$schema$value
const _dsh_jev_plugin_jev_startStageAnalysis_result$schema = () => (_dsh_jev_plugin_jev_startStageAnalysis_result$schema$value ??= z.object({
  'id': z.string(),
  'sessionId': z.string(),
  'status': z.union([z.literal("failed"), z.literal("cancelled"), z.literal("completed"), z.literal("running")]),
  'total': z.number(),
  'completed': z.number(),
  'failed': z.number(),
  'cancelled': z.number(),
  'failure': z.union([z.undefined(), z.object({
  'code': z.string(),
  'message': z.string(),
})]).optional(),
}))
let _dsh_jev_plugin_jev_testConnection_parameter_0$schema$value
const _dsh_jev_plugin_jev_testConnection_parameter_0$schema = () => (_dsh_jev_plugin_jev_testConnection_parameter_0$schema$value ??= z.object({
  'connectionId': z.union([z.literal("jev"), z.literal("luna-openrouter"), z.literal("luna-openai")]),
  'baseUrl': z.string(),
  'model': z.string(),
  'credentialRef': z.string(),
  'timeoutMs': z.number(),
}))
let _dsh_jev_plugin_jev_testConnection_result$schema$value
const _dsh_jev_plugin_jev_testConnection_result$schema = () => (_dsh_jev_plugin_jev_testConnection_result$schema$value ??= z.object({
  'connection': z.object({
  'connectionId': z.union([z.literal("jev"), z.literal("luna-openrouter"), z.literal("luna-openai")]),
  'baseUrl': z.string(),
  'model': z.string(),
  'credentialRef': z.string(),
  'timeoutMs': z.number(),
}),
  'ok': z.boolean(),
  'latencyMs': z.number(),
  'recordId': z.string(),
  'failure': z.union([z.undefined(), z.object({
  'code': z.string(),
  'message': z.string(),
})]).optional(),
}))

export const TYPERT = {
  package: '@dsh-jev/plugin',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@dsh-jev/plugin#jev/cancelStageAnalysis',
      service: 'jev',
      namespace: 'jev',
      method: 'cancelStageAnalysis',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'batchId',
          wire: 'batchId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-jev/plugin#jev/cancelStageAnalysis:batchId',
            create: _dsh_jev_plugin_jev_cancelStageAnalysis_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-jev/plugin#jev/cancelStageAnalysis:result',
        create: _dsh_jev_plugin_jev_cancelStageAnalysis_result$schema,
      },
      sourceLocation: {"file":"packages/jev/src/index.ts","line":218,"column":3},
    },
    {
      id: '@dsh-jev/plugin#jev/getCredentialStatus',
      service: 'jev',
      namespace: 'jev',
      method: 'getCredentialStatus',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'connection',
          wire: 'connection',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-jev/plugin/types#JevConnectionIdentity',
            create: _dsh_jev_plugin_jev_getCredentialStatus_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-jev/plugin/types#JevCredentialStatus',
        create: _dsh_jev_plugin_jev_getCredentialStatus_result$schema,
      },
      sourceLocation: {"file":"packages/jev/src/index.ts","line":228,"column":9},
    },
    {
      id: '@dsh-jev/plugin#jev/getRecord',
      service: 'jev',
      namespace: 'jev',
      method: 'getRecord',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-jev/plugin#jev/getRecord:id',
            create: _dsh_jev_plugin_jev_getRecord_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-jev/plugin#jev/getRecord:result',
        create: _dsh_jev_plugin_jev_getRecord_result$schema,
      },
      sourceLocation: {"file":"packages/jev/src/index.ts","line":190,"column":9},
    },
    {
      id: '@dsh-jev/plugin#jev/getStageAnalysisRecord',
      service: 'jev',
      namespace: 'jev',
      method: 'getStageAnalysisRecord',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'sessionId',
          wire: 'sessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-jev/plugin#jev/getStageAnalysisRecord:sessionId',
            create: _dsh_jev_plugin_jev_getStageAnalysisRecord_parameter_0$schema,
          },
        },
        {
          name: 'stepId',
          wire: 'stepId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-jev/plugin#jev/getStageAnalysisRecord:stepId',
            create: _dsh_jev_plugin_jev_getStageAnalysisRecord_parameter_1$schema,
          },
        },
        {
          name: 'recordId',
          wire: 'recordId',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-jev/plugin#jev/getStageAnalysisRecord:recordId',
            create: _dsh_jev_plugin_jev_getStageAnalysisRecord_parameter_2$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-jev/plugin#jev/getStageAnalysisRecord:result',
        create: _dsh_jev_plugin_jev_getStageAnalysisRecord_result$schema,
      },
      sourceLocation: {"file":"packages/jev/src/index.ts","line":222,"column":3},
    },
    {
      id: '@dsh-jev/plugin#jev/getStageNavigation',
      service: 'jev',
      namespace: 'jev',
      method: 'getStageNavigation',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'sessionId',
          wire: 'sessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-jev/plugin#jev/getStageNavigation:sessionId',
            create: _dsh_jev_plugin_jev_getStageNavigation_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-jev/plugin/stage-types#StageNavigationSnapshot',
        create: _dsh_jev_plugin_jev_getStageNavigation_result$schema,
      },
      sourceLocation: {"file":"packages/jev/src/index.ts","line":206,"column":3},
    },
    {
      id: '@dsh-jev/plugin#jev/listFeatures',
      service: 'jev',
      namespace: 'jev',
      method: 'listFeatures',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-jev/plugin#jev/listFeatures:result',
        create: _dsh_jev_plugin_jev_listFeatures_result$schema,
      },
      sourceLocation: {"file":"packages/jev/src/index.ts","line":174,"column":9},
    },
    {
      id: '@dsh-jev/plugin#jev/listRecords',
      service: 'jev',
      namespace: 'jev',
      method: 'listRecords',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'filter',
          wire: 'filter',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-jev/plugin/types#JevRecordFilter',
            create: _dsh_jev_plugin_jev_listRecords_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-jev/plugin/types#JevRecordPage',
        create: _dsh_jev_plugin_jev_listRecords_result$schema,
      },
      sourceLocation: {"file":"packages/jev/src/index.ts","line":181,"column":9},
    },
    {
      id: '@dsh-jev/plugin#jev/setCredential',
      service: 'jev',
      namespace: 'jev',
      method: 'setCredential',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'connection',
          wire: 'connection',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-jev/plugin/types#JevConnectionIdentity',
            create: _dsh_jev_plugin_jev_setCredential_parameter_0$schema,
          },
        },
        {
          name: 'value',
          wire: 'value',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-jev/plugin#jev/setCredential:value',
            create: _dsh_jev_plugin_jev_setCredential_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-jev/plugin/types#JevCredentialStatus',
        create: _dsh_jev_plugin_jev_setCredential_result$schema,
      },
      sourceLocation: {"file":"packages/jev/src/index.ts","line":236,"column":9},
    },
    {
      id: '@dsh-jev/plugin#jev/startStageAnalysis',
      service: 'jev',
      namespace: 'jev',
      method: 'startStageAnalysis',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-jev/plugin/stage-types#StageAnalysisRequest',
            create: _dsh_jev_plugin_jev_startStageAnalysis_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-jev/plugin/stage-types#StageBatchState',
        create: _dsh_jev_plugin_jev_startStageAnalysis_result$schema,
      },
      sourceLocation: {"file":"packages/jev/src/index.ts","line":212,"column":3},
    },
    {
      id: '@dsh-jev/plugin#jev/testConnection',
      service: 'jev',
      namespace: 'jev',
      method: 'testConnection',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'connection',
          wire: 'connection',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-jev/plugin/types#JevConnectionIdentity',
            create: _dsh_jev_plugin_jev_testConnection_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-jev/plugin/types#JevProbeResult',
        create: _dsh_jev_plugin_jev_testConnection_result$schema,
      },
      sourceLocation: {"file":"packages/jev/src/index.ts","line":246,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "One profile's public judgment service and browser Remote namespace.",
        "summary": "One profile's public judgment service and browser Remote namespace.",
        "tags": [],
        "jsDoc": "/** One profile's public judgment service and browser Remote namespace. */",
        "key": "jev",
        "exportName": "JevService",
        "members": [
          {
            "kind": "method",
            "name": "registerFeature",
            "signature": "registerFeature(feature: JevFeatureDefinition): () => void",
            "summary": "Register a consumer feature for this Host lifetime; the caller owns the disposer.",
            "jsDoc": "/** Register a consumer feature for this Host lifetime; the caller owns the disposer. */"
          },
          {
            "kind": "method",
            "name": "listFeatures",
            "signature": "@Remote('listFeatures') async listFeatures(): Promise<JevFeatureView[]>",
            "summary": "Current registrations, with unknown and newly registered ids disabled by default.",
            "jsDoc": "/** Current registrations, with unknown and newly registered ids disabled by default. */"
          },
          {
            "kind": "method",
            "name": "listRecords",
            "signature": "@Remote('listRecords') async listRecords(filter: JevRecordFilter): Promise<JevRecordPage>",
            "summary": "Query only the current profile, with bounded page size and optional filters.",
            "jsDoc": "/** Query only the current profile, with bounded page size and optional filters. */"
          },
          {
            "kind": "method",
            "name": "getRecord",
            "signature": "@Remote('getRecord') async getRecord(id: string): Promise<JevRecordDetail | null>",
            "summary": "Read one current-profile operation after the list has identified it.",
            "jsDoc": "/** Read one current-profile operation after the list has identified it. */"
          },
          {
            "kind": "method",
            "name": "registerStageNavigation",
            "signature": "registerStageNavigation(manager: StageNavigationManager): () => void",
            "summary": "Bind the optional Host stage consumer while its plugin row is active.",
            "jsDoc": "/** Bind the optional Host stage consumer while its plugin row is active. */"
          },
          {
            "kind": "method",
            "name": "getStageNavigation",
            "signature": "@Remote('getStageNavigation') getStageNavigation(sessionId: string, signal: AbortSignal): Promise<StageNavigationSnapshot>",
            "summary": "Read one complete authorized Session cut and its auxiliary stage results.",
            "jsDoc": "/** Read one complete authorized Session cut and its auxiliary stage results. */"
          },
          {
            "kind": "method",
            "name": "startStageAnalysis",
            "signature": "@Remote('startStageAnalysis') startStageAnalysis(request: StageAnalysisRequest): Promise<StageBatchState>",
            "summary": "Start only a user-requested batch; returning does not await model calls.",
            "jsDoc": "/** Start only a user-requested batch; returning does not await model calls. */"
          },
          {
            "kind": "method",
            "name": "cancelStageAnalysis",
            "signature": "@Remote('cancelStageAnalysis') cancelStageAnalysis(batchId: string): Promise<void>",
            "summary": "Cancel auxiliary requests without cancelling the native Agent.",
            "jsDoc": "/** Cancel auxiliary requests without cancelling the native Agent. */"
          },
          {
            "kind": "method",
            "name": "getStageAnalysisRecord",
            "signature": "@Remote('getStageAnalysisRecord') getStageAnalysisRecord(sessionId: string, stepId: string, recordId?: string): Promise<StageAnalysisRecord | null>",
            "summary": "Load exact persisted input and raw Jev answer for one selected step.",
            "jsDoc": "/** Load exact persisted input and raw Jev answer for one selected step. */"
          },
          {
            "kind": "method",
            "name": "getCredentialStatus",
            "signature": "@Remote('getCredentialStatus') async getCredentialStatus(connection: JevConnectionIdentity): Promise<JevCredentialStatus>",
            "summary": "Report credential presence, source, and writability without its value.",
            "jsDoc": "/** Report credential presence, source, and writability without its value. */"
          },
          {
            "kind": "method",
            "name": "setCredential",
            "signature": "@Remote('setCredential') async setCredential(connection: JevConnectionIdentity, value: string): Promise<JevCredentialStatus>",
            "summary": "Save or replace the current profile's configured credential reference.",
            "jsDoc": "/** Save or replace the current profile's configured credential reference. */"
          },
          {
            "kind": "method",
            "name": "testConnection",
            "signature": "@Remote('testConnection') async testConnection(connection: JevConnectionIdentity, signal: AbortSignal): Promise<JevProbeResult>",
            "summary": "Run one fixed diagnostic without a business feature or user state.",
            "jsDoc": "/** Run one fixed diagnostic without a business feature or user state. */"
          },
          {
            "kind": "method",
            "name": "judge",
            "signature": "judge(options: JevJudgeOptions): Promise<JevJudgeResult>",
            "summary": "Judge one dependent operation; only a human retry invokes `refresh` again.",
            "jsDoc": "/** Judge one dependent operation; only a human retry invokes `refresh` again. */"
          },
          {
            "kind": "method",
            "name": "judgeOnce",
            "signature": "judgeOnce(options: JevJudgeOnceOptions): Promise<JevJudgeOnceResult>",
            "summary": "Make one logged attempt without human waiting or automatic retry.",
            "jsDoc": "/** Make one logged attempt without human waiting or automatic retry. Only `ok` permits adoption. */"
          },
          {
            "kind": "method",
            "name": "isFeatureEnabled",
            "signature": "isFeatureEnabled(featureId: string): boolean",
            "summary": "Read this profile's current enablement synchronously; absent feature ids are disabled.",
            "jsDoc": "/** Read this profile's current enablement synchronously; absent feature ids are disabled. */"
          },
          {
            "kind": "method",
            "name": "onFeatureStateChange",
            "signature": "onFeatureStateChange(listener: (features: Readonly<Record<string, boolean>>) => void): () => void",
            "summary": "Observe committed feature-setting changes synchronously; the consumer owns the disposer.",
            "jsDoc": "/** Observe committed feature-setting changes synchronously; the consumer owns the disposer. */"
          },
          {
            "kind": "method",
            "name": "stageConnectionIdentity",
            "signature": "stageConnectionIdentity(): Omit<JevConnectionIdentity, 'connectionId'> & { connectionId?: JevConnectionId }",
            "summary": "Stable non-secret connection settings used to decide whether an old stage result is current.",
            "jsDoc": "/** Stable non-secret connection settings used to decide whether an old stage result is current. */"
          },
          {
            "kind": "method",
            "name": "stageConnections",
            "signature": "stageConnections(): readonly JevConnectionIdentity[]",
            "summary": "All saved references must be checked before historical input is released to a provider.",
            "jsDoc": "/** All saved references must be checked before historical input is released to a provider. */"
          },
          {
            "kind": "method",
            "name": "judgmentConnectionIdentity",
            "signature": "judgmentConnectionIdentity(): JevConnectionIdentity",
            "summary": "Current saved connection without authentication values.",
            "jsDoc": "/** Current saved connection without authentication values. */"
          },
          {
            "kind": "method",
            "name": "recordInterrupted",
            "signature": "recordInterrupted(featureId: string, link: JevOperationLink): Promise<JevRecordDetail>",
            "summary": "Record interrupted input without a model call, human question, or attempt; stable message links are idempotent.",
            "jsDoc": "/** Record interrupted input without a model call, human question, or attempt; stable message links are idempotent. */"
          },
          {
            "kind": "method",
            "name": "recordRuleObservation",
            "signature": "recordRuleObservation(featureId: string, link: JevOperationLink): Promise<JevRecordDetail>",
            "summary": "Record one rules-only candidate result with zero model attempts.",
            "jsDoc": "/** Record one rules-only candidate result with zero model attempts. */"
          },
          {
            "kind": "method",
            "name": "noteFailure",
            "signature": "async noteFailure(operationId: string, code: string, message: string): Promise<void>",
            "summary": "Attach a consumer fallback reason to an already failed or cancelled operation.",
            "jsDoc": "/** Attach a consumer fallback reason to an already failed or cancelled operation. */"
          },
          {
            "kind": "method",
            "name": "writeReceipt",
            "signature": "async writeReceipt(operationId: string, receipt: JevActionReceipt): Promise<JevRecordDetail>",
            "summary": "Persist one action receipt; a failed write leaves execution status unconfirmed.",
            "jsDoc": "/** Persist one action receipt; a failed write leaves execution status unconfirmed. */"
          }
        ],
        "types": [
          {
            "name": "JevActionReceipt",
            "declaration": "export interface JevActionReceipt {\n    id: string;\n    status: JevActionStatus;\n    reason?: string;\n    at: string;\n}"
          },
          {
            "name": "JevActionStatus",
            "declaration": "export type JevActionStatus = 'unconfirmed' | 'not-adopted' | 'cancelled' | 'executed' | 'execution-failed' | 'observed';"
          },
          {
            "name": "JevAnswer",
            "declaration": "export type JevAnswer = { id: string; kind: 'choice'; optionId: string; probabilities?: Record<string, number>; confidence?: number; legend?: Json; } | { id: string; kind: 'score'; value: number; probabilities?: Record<string, number>; confidence?: number; legend?: Json; } | { id: string; kind: 'noul'; probability: number; confidence?: number; legend?: Json; };"
          },
          {
            "name": "JevAttemptRecord",
            "declaration": "export interface JevAttemptRecord {\n    id: string;\n    startedAt: string;\n    settledAt?: string;\n    latencyMs?: number;\n    connection: { baseUrl: string; model: string; credentialRef: string; connectionId?: JevConnectionId; };\n    request: JevRequest;\n    status: JevRecordStatus;\n    rawResponse?: Json;\n    response?: JevResponse;\n    interpretation?: { usable: boolean; reason?: string; };\n    failure?: { code: string; message: string; };\n    usage?: JevUsage;\n    networkRecords?: readonly JevNetworkRecord[];\n    usageComplete?: boolean;\n}"
          },
          {
            "name": "JevConnectionId",
            "declaration": "export type JevConnectionId = 'jev' | 'luna-openrouter' | 'luna-openai';"
          },
          {
            "name": "JevConnectionIdentity",
            "declaration": "export interface JevConnectionIdentity {\n    connectionId: JevConnectionId;\n    baseUrl: string;\n    model: string;\n    credentialRef: string;\n    timeoutMs: number;\n}"
          },
          {
            "name": "JevCredentialStatus",
            "declaration": "export interface JevCredentialStatus {\n    connection: JevConnectionIdentity;\n    configured: boolean;\n    writable: boolean;\n    source?: string;\n}"
          },
          {
            "name": "JevFeatureDefinition",
            "declaration": "export interface JevFeatureDefinition {\n    id: string;\n    name: string;\n    description: string;\n    settingsDescription?: string;\n}"
          },
          {
            "name": "JevFeatureView",
            "declaration": "export interface JevFeatureView extends JevFeatureDefinition {\n    enabled: boolean;\n}"
          },
          {
            "name": "JevInput",
            "declaration": "export type JevInput = string | readonly Json[] | { readonly [key: string]: Json; };"
          },
          {
            "name": "JevJudgeOnceOptions",
            "declaration": "export type JevJudgeOnceOptions = Omit<JevJudgeOptions, 'agent'> & { agent?: Agent; connection?: JevConnectionIdentity; };"
          },
          {
            "name": "JevJudgeOnceResult",
            "declaration": "export type JevJudgeOnceResult = JevJudgeResult | { kind: 'failed'; operationId?: string; failure: { code: string; message: string; }; };"
          },
          {
            "name": "JevJudgeOptions",
            "declaration": "export interface JevJudgeOptions {\n    featureId: string;\n    link: JevOperationLink;\n    agent: Agent;\n    refresh: (signal: AbortSignal) => JevRequest | Promise<JevRequest>;\n    interpret?: (response: JevResponse, signal: AbortSignal) => { usable: true; } | { usable: false; reason: string; } | Promise<{ usable: true; } | { usable: false; reason: string; }>;\n    canAdopt?: (response: JevResponse, signal: AbortSignal) => true | string | Promise<true | string>;\n    signal?: AbortSignal;\n}"
          },
          {
            "name": "JevJudgeResult",
            "declaration": "export type JevJudgeResult = { kind: 'ok'; operationId: string; attemptId: string; response: JevResponse; } | { kind: 'cancelled'; operationId: string; } | { kind: 'not-adopted'; operationId: string; reason: string; };"
          },
          {
            "name": "JevNetworkRecord",
            "declaration": "export interface JevNetworkRecord {\n    id: string;\n    questionIds: readonly string[];\n    requestBody: Json;\n    startedAt: string;\n    dispatchedAt?: string;\n    settledAt?: string;\n    status: 'pending' | 'succeeded' | 'failed';\n    httpStatus?: number;\n    rawResponseText?: string;\n    rawResponse?: Json;\n    returnedModel?: string;\n    requestId?: string;\n    usage?: JevUsage;\n    failure?: { code: string; message: string; };\n}"
          },
          {
            "name": "JevOperationLink",
            "declaration": "export interface JevOperationLink {\n    sessionId?: string;\n    runId?: string;\n    stepId?: string;\n    inputVersion?: string;\n}"
          },
          {
            "name": "JevProbeResult",
            "declaration": "export interface JevProbeResult {\n    connection: JevConnectionIdentity;\n    ok: boolean;\n    latencyMs: number;\n    recordId: string;\n    failure?: { code: string; message: string; };\n}"
          },
          {
            "name": "JevQuestion",
            "declaration": "export type JevQuestion = { id: string; kind: 'choice'; prompt: JevInput; options: readonly { id: string; description: JevInput | null; }[]; } | { id: string; kind: 'score'; prompt: JevInput; levels: readonly (JevInput | null)[]; } | { id: string; kind: 'noul'; prompt: JevInput; criteria?: { true?: JevInput | null; false?: JevInput | null; }; };"
          },
          {
            "name": "JevRecordDetail",
            "declaration": "export interface JevRecordDetail extends JevRecordSummary {\n    link: JevOperationLink;\n    attemptRecords: readonly JevAttemptRecord[];\n    receipts: readonly JevActionReceipt[];\n    failure?: { code: string; message: string; };\n}"
          },
          {
            "name": "JevRecordFilter",
            "declaration": "export interface JevRecordFilter {\n    featureId?: string;\n    status?: JevRecordStatus;\n    sessionId?: string;\n    cursor?: string;\n    limit?: number;\n}"
          },
          {
            "name": "JevRecordPage",
            "declaration": "export interface JevRecordPage {\n    items: readonly JevRecordSummary[];\n    nextCursor?: string;\n}"
          },
          {
            "name": "JevRecordStatus",
            "declaration": "export type JevRecordStatus = 'pending' | 'waiting' | 'succeeded' | 'failed' | 'cancelled' | 'interrupted';"
          },
          {
            "name": "JevRecordSummary",
            "declaration": "export interface JevRecordSummary {\n    id: string;\n    featureId: string;\n    sessionId?: string;\n    status: JevRecordStatus;\n    startedAt: string;\n    updatedAt: string;\n    attempts: number;\n    actionStatus?: JevActionStatus;\n    diagnostic: boolean;\n}"
          },
          {
            "name": "JevRequest",
            "declaration": "export interface JevRequest {\n    state: Json;\n    questions: readonly JevQuestion[];\n}"
          },
          {
            "name": "JevResponse",
            "declaration": "export interface JevResponse {\n    answers: readonly JevAnswer[];\n}"
          },
          {
            "name": "JevUsage",
            "declaration": "export interface JevUsage {\n    inputTokens?: number;\n    outputTokens?: number;\n}"
          },
          {
            "name": "Json",
            "declaration": "export type Json = null | boolean | number | string | readonly Json[] | { readonly [key: string]: Json; };"
          },
          {
            "name": "StageAnalysisRecord",
            "declaration": "export interface StageAnalysisRecord extends StageAnalysisSummary {\n    id: string;\n    sessionId: string;\n    stepId: string;\n    revision: number;\n    sourceFingerprint: string;\n    ruleVersion: string;\n    request?: JevRequest;\n    response?: JevResponse;\n    rawResponse?: Json;\n    connection?: JevAttemptRecord['connection'];\n    networkRecords?: JevAttemptRecord['networkRecords'];\n    usage?: JevAttemptRecord['usage'];\n    usageComplete?: boolean;\n}"
          },
          {
            "name": "StageAnalysisRequest",
            "declaration": "export interface StageAnalysisRequest {\n    sessionId: string;\n    scope: { kind: 'turn'; turn: number; } | { kind: 'all'; };\n    mode: 'missing' | 'retry-failed' | 'refresh';\n}"
          },
          {
            "name": "StageAnalysisStatus",
            "declaration": "export type StageAnalysisStatus = 'unanalysed' | 'pending' | 'succeeded' | 'failed' | 'cancelled' | 'interrupted' | 'stale' | 'unavailable';"
          },
          {
            "name": "StageAnalysisSummary",
            "declaration": "export interface StageAnalysisSummary {\n    status: StageAnalysisStatus;\n    label?: StageLabel;\n    confidence?: number;\n    probabilities?: Record<string, number>;\n    model?: string;\n    configuredModel?: string;\n    connectionId?: JevConnectionId;\n    recordId?: string;\n    operationId?: string;\n    failure?: { code: string; message: string; };\n    updatedAt?: string;\n    previousResult?: StagePreviousResult;\n}"
          },
          {
            "name": "StageBatchState",
            "declaration": "export interface StageBatchState {\n    id: string;\n    sessionId: string;\n    status: 'running' | 'completed' | 'cancelled' | 'failed';\n    total: number;\n    completed: number;\n    failed: number;\n    cancelled: number;\n    failure?: { code: string; message: string; };\n}"
          },
          {
            "name": "StageLabel",
            "declaration": "export type StageLabel = 'input_parsing' | 'problem_understanding' | 'solution_planning' | 'implementation' | 'review_validation' | 'delivery_finalization' | 'mixed' | 'unknown';"
          },
          {
            "name": "StageMessage",
            "declaration": "export interface StageMessage {\n    seq: number;\n    content: readonly ContentBlock[];\n}"
          },
          {
            "name": "StageNavigationManager",
            "declaration": "export class StageNavigationManager {\n    read(sessionId: string, signal: AbortSignal): Promise<StageNavigationSnapshot>;\n    detail(sessionId: string, stepId: string, requestedRecordId?: string): Promise<StageAnalysisRecord | null>;\n    start(request: StageAnalysisRequest): Promise<StageBatchState>;\n    cancel(batchId: string): Promise<void>;\n    stop(): Promise<void>;\n    cancelRunning(): void;\n}"
          },
          {
            "name": "StageNavigationSnapshot",
            "declaration": "export interface StageNavigationSnapshot {\n    sessionId: string;\n    cursor: number;\n    featureEnabled: boolean;\n    turns: readonly StageTurn[];\n    batch?: StageBatchState;\n}"
          },
          {
            "name": "StagePreviousResult",
            "declaration": "export interface StagePreviousResult {\n    recordId: string;\n    label: StageLabel;\n    stale: boolean;\n    confidence?: number;\n    probabilities?: Record<string, number>;\n    model?: string;\n    configuredModel?: string;\n    connectionId?: JevConnectionId;\n    updatedAt?: string;\n}"
          },
          {
            "name": "StageStep",
            "declaration": "export interface StageStep {\n    id: string;\n    turn: number;\n    step: number;\n    startSeq: number;\n    endSeq?: number;\n    status: 'complete' | 'terminal-partial' | 'in-progress';\n    classifiable: boolean;\n    materialStatus: 'ready' | 'IN_PROGRESS' | 'NO_MATERIAL' | 'MATERIAL_TOO_LARGE';\n    assistant?: StageMessage & { interrupted: boolean; };\n    messages: readonly (StageMessage & { interrupted: boolean; })[];\n    tools: readonly StageToolCall[];\n    attemptSeqs: readonly number[];\n    analysis: StageAnalysisSummary;\n}"
          },
          {
            "name": "StageToolCall",
            "declaration": "export interface StageToolCall {\n    callId: string;\n    name: string;\n    arguments: string;\n    seq: number;\n    dispatched: boolean;\n    result?: StageMessage & { isError: boolean; error?: { name: string; code: string; reason?: string; }; };\n}"
          },
          {
            "name": "StageTurn",
            "declaration": "export interface StageTurn {\n    id: string;\n    turn: number;\n    startSeq: number;\n    endSeq?: number;\n    reason?: TurnEndReason;\n    requests: readonly StageMessage[];\n    steps: readonly StageStep[];\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
