/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { StageAnalysisRecord, StageAnalysisRequest, StageBatchState, StageNavigationSnapshot } from '@dsh-jev/plugin/stage-types'
import type { JevConnectionIdentity, JevCredentialStatus, JevFeatureView, JevProbeResult, JevRecordDetail, JevRecordFilter, JevRecordPage } from '@dsh-jev/plugin/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6a6576 {
    cancelStageAnalysis: (batchId: string) => Promise<RemoteResult<void>>
    getCredentialStatus: (connection: JevConnectionIdentity) => Promise<RemoteResult<JevCredentialStatus>>
    getRecord: (id: string) => Promise<RemoteResult<JevRecordDetail | null>>
    getStageAnalysisRecord: (sessionId: string, stepId: string, recordId?: string) => Promise<RemoteResult<StageAnalysisRecord | null>>
    getStageNavigation: (sessionId: string, signal?: AbortSignal) => Promise<RemoteResult<StageNavigationSnapshot>>
    listFeatures: () => Promise<RemoteResult<JevFeatureView[]>>
    listRecords: (filter: JevRecordFilter) => Promise<RemoteResult<JevRecordPage>>
    setCredential: (connection: JevConnectionIdentity, value: string) => Promise<RemoteResult<JevCredentialStatus>>
    startStageAnalysis: (request: StageAnalysisRequest) => Promise<RemoteResult<StageBatchState>>
    testConnection: (connection: JevConnectionIdentity, signal?: AbortSignal) => Promise<RemoteResult<JevProbeResult>>
  }
  interface TypertRemoteMap {
    'jev/cancelStageAnalysis': (batchId: string) => Promise<RemoteResult<void>>
    'jev/getCredentialStatus': (connection: JevConnectionIdentity) => Promise<RemoteResult<JevCredentialStatus>>
    'jev/getRecord': (id: string) => Promise<RemoteResult<JevRecordDetail | null>>
    'jev/getStageAnalysisRecord': (sessionId: string, stepId: string, recordId?: string) => Promise<RemoteResult<StageAnalysisRecord | null>>
    'jev/getStageNavigation': (sessionId: string, signal?: AbortSignal) => Promise<RemoteResult<StageNavigationSnapshot>>
    'jev/listFeatures': () => Promise<RemoteResult<JevFeatureView[]>>
    'jev/listRecords': (filter: JevRecordFilter) => Promise<RemoteResult<JevRecordPage>>
    'jev/setCredential': (connection: JevConnectionIdentity, value: string) => Promise<RemoteResult<JevCredentialStatus>>
    'jev/startStageAnalysis': (request: StageAnalysisRequest) => Promise<RemoteResult<StageBatchState>>
    'jev/testConnection': (connection: JevConnectionIdentity, signal?: AbortSignal) => Promise<RemoteResult<JevProbeResult>>
  }
  interface TypertRemoteNamespaceMap {
    'jev': TypertRemoteNamespace$6a6576
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
